# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor.shape, tensor

(torch.Size([7, 7]),
 tensor([[8.3881e-01, 6.8385e-02, 8.8621e-01, 9.2900e-01, 2.1379e-01, 3.6061e-01,
          7.9036e-01],
         [5.2136e-04, 9.2252e-01, 1.2492e-01, 9.5491e-01, 3.7381e-01, 1.4210e-01,
          2.8193e-01],
         [9.8076e-01, 5.6368e-01, 2.4461e-01, 9.6733e-01, 3.1728e-01, 7.5265e-01,
          2.5536e-01],
         [9.0309e-01, 9.5615e-01, 7.4284e-01, 5.2554e-01, 9.5792e-01, 5.5986e-02,
          5.9580e-01],
         [4.6009e-01, 8.4900e-01, 7.2065e-01, 9.5011e-01, 2.2885e-02, 1.0367e-01,
          5.5646e-01],
         [6.7455e-01, 3.3410e-01, 3.2362e-03, 5.8709e-01, 9.7949e-01, 5.5360e-01,
          7.5715e-01],
         [2.6682e-01, 7.0925e-01, 4.9166e-01, 7.7322e-01, 7.7915e-01, 7.8897e-01,
          1.5624e-01]]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_two = torch.rand(1,7)

print(f"1st tensor = {tensor}")
print(f"2nd tensor = {tensor_two}")

# Perform matrix multiplication
multi_tensor = tensor @ tensor_two.T
multi_tensor , multi_tensor.shape

1st tensor = tensor([[8.3881e-01, 6.8385e-02, 8.8621e-01, 9.2900e-01, 2.1379e-01, 3.6061e-01,
         7.9036e-01],
        [5.2136e-04, 9.2252e-01, 1.2492e-01, 9.5491e-01, 3.7381e-01, 1.4210e-01,
         2.8193e-01],
        [9.8076e-01, 5.6368e-01, 2.4461e-01, 9.6733e-01, 3.1728e-01, 7.5265e-01,
         2.5536e-01],
        [9.0309e-01, 9.5615e-01, 7.4284e-01, 5.2554e-01, 9.5792e-01, 5.5986e-02,
         5.9580e-01],
        [4.6009e-01, 8.4900e-01, 7.2065e-01, 9.5011e-01, 2.2885e-02, 1.0367e-01,
         5.5646e-01],
        [6.7455e-01, 3.3410e-01, 3.2362e-03, 5.8709e-01, 9.7949e-01, 5.5360e-01,
         7.5715e-01],
        [2.6682e-01, 7.0925e-01, 4.9166e-01, 7.7322e-01, 7.7915e-01, 7.8897e-01,
         1.5624e-01]])
2nd tensor = tensor([[0.8728, 0.5392, 0.1755, 0.2255, 0.8065, 0.1195, 0.9020]])


(tensor([[2.0624],
         [1.3078],
         [1.9971],
         [2.8693],
         [1.7328],
         [2.4409],
         [1.7395]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0


# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(7,7)
print(f"tensor A: {tensor_A}")

# torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(1,7)
print(f"tensor B: {tensor_B}")

# Matrix multiply tensors
mutli_tensor = tensor_A @ tensor_B.T
# print(f"multi tensor: {multi_tensor}")
mutli_tensor

tensor A: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor B: tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
RANDOM_SEED_GPU = torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
RANDOM_SEED_GPU = torch.manual_seed(1234)

# Check for access to GPU
print(f"access to GPU: {torch.cuda.is_available()}")


# Create two random tensors on GPU
tensor_A_GPU = torch.rand(2,3).cuda()
tensor_B_GPU = torch.rand(2,3).cuda()

tensor_A_GPU, tensor_B_GPU

access to GPU: True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B

matmul_matrix_GPU = tensor_A_GPU @ tensor_B_GPU.T
matmul_matrix_GPU

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = matmul_matrix_GPU.max()
max
# Find min
min = matmul_matrix_GPU.min()
max,min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_index = matmul_matrix_GPU.argmax()

# Find arg min
min_index = matmul_matrix_GPU.argmin()

max_index, min_index

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
RANDOM_SEED_SEVEN = 7

# Create random tensor
torch.manual_seed(RANDOM_SEED_SEVEN)
random_tensor = torch.rand(1,1,1,10)

print(f"1st random_tensor: \n{random_tensor} \n size {random_tensor.shape}")


# Remove single dimensions
squeezed_random_tensor = random_tensor.squeeze()

# Print out tensors and their shapes
print(f"2nd random_tensor: \n{squeezed_random_tensor} \n size {squeezed_random_tensor.shape}")

1st random_tensor: 
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) 
 size torch.Size([1, 1, 1, 10])
2nd random_tensor: 
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) 
 size torch.Size([10])
